# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-06 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('company_address', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=50)),
                ('set_time', models.CharField(max_length=50)),
                ('company_introduction', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'company_info',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('path', models.FileField(upload_to='./upload')),
            ],
            options={
                'db_table': 'img',
            },
        ),
        migrations.CreateModel(
            name='People_Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'people_discusses',
            },
        ),
        migrations.CreateModel(
            name='Positions_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('set_time', models.DateTimeField()),
                ('company_address', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('company_introduction', models.TextField()),
                ('skills', models.TextField()),
                ('people_number', models.IntegerField(default=0)),
                ('company_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'positions_info',
            },
        ),
        migrations.CreateModel(
            name='Root_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'root_user',
            },
        ),
        migrations.CreateModel(
            name='School_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=200)),
                ('real_name', models.CharField(max_length=50)),
                ('school_address', models.CharField(max_length=300)),
                ('college', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tag', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'school_info',
            },
        ),
        migrations.CreateModel(
            name='Student_Employment_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('college', models.CharField(max_length=200)),
                ('professional', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=50)),
                ('company_phone', models.CharField(max_length=50)),
                ('company_header', models.CharField(max_length=100)),
                ('company_header_phone', models.BigIntegerField()),
                ('phone_self', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('birth_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'student_employment_info',
            },
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('college', models.CharField(max_length=200)),
                ('professional', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('signature', models.CharField(max_length=300)),
                ('parent_phone', models.BigIntegerField()),
                ('birth_date', models.DateTimeField()),
                ('tag', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
