# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='path',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='student_employment_info',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
