# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-12 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20180912_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='birth_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
