# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-12 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180912_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions_info',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
